/*************************************************************************

    chm2web Help Index Library 2.8
    Copyright (c) 2002-2008 A!K Research Labs (http://www.aklabs.com)  
    http://chm2web.aklabs.com - HTML Help Conversion Utility

    Tested with: Internet Explorer 6+, Opera 7+, FireFox 2+

    ATTENTION! You can use this library only with web help system 
               generated by chm2web software.  
               
**************************************************************************/


var chm2webdoct = false;

function FindFrame(frameName, start)
{
 if(start==null) return null;

 var resframe = null;
 var frames = start.frames;
 if(frames.length==0) return null;

 for(var i=0; i<frames.length; i++)
 {
    tmpFrame = frames[i];

    try { tmpFrameName = tmpFrame.name; }
    catch (e) { continue; }    

    if(tmpFrameName.toUpperCase() == frameName.toUpperCase())
    {
      resframe = frames[i];
    } else {
      resframe = FindFrame(frameName, tmpFrame);
    }
    if (resframe != null) return resframe;
 } return null;
}

function pageWidth() {
  return chm2webdoct.innerWidth != null ? 
  chm2webdoct.innerWidth : chm2webdoct.documentElement && chm2webdoct.documentElement.clientWidth ? 
  chm2webdoct.documentElement.clientWidth : chm2webdoct.body != null ? 
  chm2webdoct.body.clientWidth : null;
}

function pageHeight() {
  return chm2webdoct.innerHeight != null? 
  chm2webdoct.innerHeight : chm2webdoct.documentElement && chm2webdoct.documentElement.clientHeight ? 
  chm2webdoct.documentElement.clientHeight : chm2webdoct.body != null? 
  chm2webdoct.body.clientHeight : null;
}

function topPosition() {
  return typeof chm2webdoct.pageYOffset != 'undefined' ? 
   chm2webdoct.pageYOffset : chm2webdoct.documentElement && chm2webdoct.documentElement.scrollTop ? 
   chm2webdoct.documentElement.scrollTop : chm2webdoct.body.scrollTop ? 
   chm2webdoct.body.scrollTop : 0;
}

function leftPosition() {
  return typeof window.pageXOffset != 'undefined' ? 
   window.pageXOffset : chm2webdoct.documentElement && chm2webdoct.documentElement.scrollLeft ? 
   chm2webdoct.documentElement.scrollLeft : chm2webdoct.body.scrollLeft ? 
   chm2webdoct.body.scrollLeft : 0;
}

function dialogClick()
{ 
   hideDialog();
   var il = chm2webdoct.getElementById('chm2webdialog-indexlist');
   if (il.value=="") return false;
  
   var lpos = location.href.lastIndexOf("/");
   var root = lpos==-1?"":location.href.substring(0, lpos)+"/"; 
   open(root + il.value, "content");   
   return true;
   
}

function showDialog(dataarr) {
  chm2webdoct = FindFrame("content", window.top).document;

  var autohide = false;
  var dialog; 
  var dialogheader;
  var dialogclose;
  var dialogtitle;
  var dialogcontent;
  var dialogmask;
  var dialogindexlist;
  var dialoginputok;
  var dialoginputcancel;
  if(!chm2webdoct.getElementById('chm2webdialog')) {
    dialog = chm2webdoct.createElement('div');
    dialog.id = 'chm2webdialog';
    dialogheader = chm2webdoct.createElement('div');
    dialogheader.id = 'chm2webdialog-header';
    dialogtitle = chm2webdoct.createElement('div');
    dialogtitle.id = 'chm2webdialog-title';
    dialogclose = chm2webdoct.createElement('div');
    dialogclose.id = 'chm2webdialog-close'
    dialogcontent = chm2webdoct.createElement('div');
    dialogcontent.id = 'chm2webdialog-content';
    dialogmask = chm2webdoct.createElement('div');
    dialogmask.id = 'chm2webdialog-mask';
    dialogmessage = chm2webdoct.createElement('span');
    dialogmessage.id = 'chm2webdialog-message';
    dialogindexlist = chm2webdoct.createElement('select');
    dialogindexlist.id = 'chm2webdialog-indexlist';    
    dialogindexlist.size = 500;	    
    dialoginputok = chm2webdoct.createElement('input'); 
    dialoginputok.type = 'button';
    dialoginputok.id = 'chm2webdialog-ok';
    dialoginputok.value = 'Ok';
    dialoginputcancel = chm2webdoct.createElement('input'); 
    dialoginputcancel.type = 'button';
    dialoginputcancel.id = 'chm2webdialog-cancel';
    dialoginputcancel.value = 'Cancel';
   
    chm2webdoct.body.appendChild(dialogmask);
    chm2webdoct.body.appendChild(dialog);
    dialog.appendChild(dialogheader);
    dialogheader.appendChild(dialogtitle);
    dialogheader.appendChild(dialogclose);
    dialog.appendChild(dialogcontent);
    dialogcontent.appendChild(dialogmessage);
    dialogcontent.appendChild(dialogindexlist);
    dialogcontent.appendChild(dialoginputok);
    dialogcontent.appendChild(dialoginputcancel);
    dialogclose.setAttribute('onclick','hideDialog()');
    dialogclose.onclick = hideDialog;
    dialoginputok.onclick = dialogClick;
    dialoginputcancel.onclick = hideDialog;
    dialogindexlist.ondblclick = dialogClick;
  } else {
    dialog = chm2webdoct.getElementById('chm2webdialog');
    dialogheader = chm2webdoct.getElementById('chm2webdialog-header');
    dialogtitle = chm2webdoct.getElementById('chm2webdialog-title');
    dialogclose = chm2webdoct.getElementById('chm2webdialog-close');
    dialogcontent = chm2webdoct.getElementById('chm2webdialog-content');
    dialogindexlist = chm2webdoct.getElementById('chm2webdialog-indexlist');
    dialogok = chm2webdoct.getElementById('chm2webdialog-ok');
    dialogmask = chm2webdoct.getElementById('chm2webdialog-mask');
    dialogmask.style.visibility = "visible";
    dialog.style.visibility = "visible";
  }

  dialog.style.opacity = .00;
  dialog.style.filter = 'alpha(opacity=0)';
  dialog.alpha = 0;
  var width = pageWidth();
  var height = pageHeight();
  var left = leftPosition();
  var top = topPosition();
  dialog.style.width = (width- (pageWidth()/10)) + "px";
  var dialogwidth = dialog.offsetWidth;
  var dialogheight = dialog.offsetHeight;
  var topposition = top + (height / 3) - (dialogheight / 2);
  var leftposition = left + (width / 2) - (dialogwidth / 2);
  dialog.style.top = topposition + "px";
  dialog.style.left = leftposition + "px"; 

  dialogheader.className = "chm2webdialogheader";
  dialogtitle.innerHTML = "Select a Topic";
  dialogcontent.className = "chm2webdialog";
  dialogmessage.innerHTML = "Please select a topic";
  var content = chm2webdoct.body;

  dialogindexlist.innerHTML = ''; 
  for (var i = 0; i < dataarr.length; i++)
  {
    var e = chm2webdoct.createElement("OPTION");
    e.innerHTML = dataarr[i][0]; e.value = dataarr[i][1];
    dialogindexlist.appendChild(e);
  }

  dialogmask.style.height = content.offsetHeight-2 + 'px';
  dialogmask.style.width = content.offsetWidth-2 + 'px';
  dialog.timer = setInterval("fadeDialog(1)", 5);
  dialogclose.style.visibility = "visible";
}

function hideDialog() {
  var dialog = chm2webdoct.getElementById('chm2webdialog');
  clearInterval(dialog.timer);
  dialog.timer = setInterval("fadeDialog(0,window)", 5);
}

// fade-in the dialog box //
function fadeDialog(flag) {
  if(flag == null) {
    flag = 1;
  }
  var dialog = chm2webdoct.getElementById('chm2webdialog');
  var value;
  if(flag == 1) {
    value = dialog.alpha + 15;
  } else {
    value = dialog.alpha - 15;
  }
  dialog.alpha = value;
  dialog.style.opacity = (value / 100);
  dialog.style.filter = 'alpha(opacity=' + value + ')';
  if(value >= 99) {
    clearInterval(dialog.timer);
    dialog.timer = null;
  } else if(value <= 1) {
    dialog.style.visibility = "hidden";
    chm2webdoct.getElementById('chm2webdialog-mask').style.visibility = "hidden";
    clearInterval(dialog.timer);
  }
}


/*****************************************************/


function Startup()
{
  for (var i = 0; i < HelpIndex.length; i++)
  {
    var e = document.createElement("OPTION");
    var desc = HelpIndex[i][0];
    e.value = i;    
    if (desc.charAt(0)==' ') { desc = "&nbsp;&nbsp;&nbsp;&nbsp;" + desc; } 
    e.innerHTML = desc;
    document.forms[0].indexlist.appendChild(e);
  }
}

var oldS = "";

function SelectMatch(str)
{
  chmtop.c2wtopf.indexquery=str;

  var s = str.toUpperCase();
  
  if ((s == "") || (s == oldS))
    return false;

  oldS = s;

  var re = new RegExp("^"+s, "i");
  var end = document.forms[0].indexlist.length - 1;

  for (var i = 0; i <= end; i++) 
    if (document.forms[0].indexlist[i].text.match(re))
    {
      document.forms[0].indexlist[i].selected = true;
      return true;
    }
 
  return false;
}

function ShowMatch()
{
  var selindex = document.forms[0].indexlist.selectedIndex;
  var arrindex = document.forms[0].indexlist[selindex].value;
  var str = HelpIndex[arrindex][1];

  if (str.constructor.toString().indexOf("Array")>=0) { 
     showDialog(str);  
  } else {
    if (str.substr(0, 3) == "@@@") {
       str = str.substr(3); oldS = "";
       SelectMatch(str);
       return true;
    };

    if (selindex >= 0) {
      open(str, "content");
      return true;
    } else 
      return false;  
  }
}

